name: FastAPI application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DBNAME: 'mydb'
  DBHOST: 'localhost'
  DBPORT: '5432'
  DBUSER: 'postgres'
  DBPASSWORD: 'sahu'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Print environment variables
      run: |
        echo "DBHOST=${DBHOST}"
        echo "DBNAME=${DBNAME}"
        echo "DBPASSWORD=${DBPASSWORD}"
        echo "DBPORT=${DBPORT}"
        echo "DBUSER=${DBUSER}"
      shell: /usr/bin/bash -e {0}
      env:
        DBHOST: ${{ secrets.DBHOST }}
        DBNAME: ${{ secrets.DBNAME }}
        DBPASSWORD: ${{ secrets.DBPASSWORD }}
        DBPORT: ${{ secrets.DBPORT }}
        DBUSER: ${{ secrets.DBUSER }}
    - name: Run tests
      run: pytest
