name: FastAPI application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set environment variables
      run: |
        echo "DBHOST=${{ secrets.DBHOST }}" >> $GITHUB_ENV
        echo "DBNAME=${{ secrets.DBNAME }}" >> $GITHUB_ENV
        echo "DBPASSWORD=${{ secrets.DBPASSWORD }}" >> $GITHUB_ENV
        echo "DBPORT=${{ secrets.DBPORT }}" >> $GITHUB_ENV
        echo "DBUSER=${{ secrets.DBUSER }}" >> $GITHUB_ENV
    - name: Run tests
      run: pytest
