name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL: postgresql://${{secrets.DBUSER}}:${{secrets.DBPASSWORD}}@${{secrets.DBHOST}}:${{secrets.DBPORT}}/${{secrets.DBNAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{secrets.DBUSER}}
          POSTGRES_PASSWORD: ${{secrets.DBPASSWORD}}
          POSTGRES_DB: ${{secrets.DBNAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Start FastAPI server
      run: |
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5

    - name: Health check
      run: |
        curl -f http://localhost:8000/docs || exit 1
    - name: Print Secret
      run: |
        echo "Hello my name is ${{secrets.DBNAME}} what are looking for"

    - name: Run tests
      run: | 
        pytest -v --disable-warnings
